### ISSUE TITLE
Blockchair is awesome! Is it possible get API access somehow?

### ISSUE THREAD

**Issue by SuperHenkie** [Blockchair/Blockchair.Support#11]
As an online blockchain explorer, Blockchair is incredible!

Would it also be possible to get API access, i.e. to retrieve data like address or transaction details and such, through an API interface?

Basically, instead of outputting the data in a fancy web design format, just output the data in JSON or something.

**Comment by Har01d** [comment]
Thank you so much!

We have an API, but currently there’s no documentation and many things can be changed, so it’s not production ready for third parties.

As of now, you can just dig into how our front-end works using the developer tools in your browser. The front-end makes requests to the API server, and for most front-end URLs there’s an API counterparty which gives information in JSON, e.g.:
https://blockchair.com/bitcoin/blocks?s=cdd_total(desc)
https://api.blockchair.com/bitcoin/blocks?s=cdd_total(desc)

Please note that currently we have quite a straight-forward rate limiter, it’s not very smart as it doesn’t differ heavy queries from light, so please make sure that you won’t be making more than ~ a dozen queries per minute.

**Comment by JohnnyCashout** [comment]
is there an api cal equivalent for 'getreceivedbyaddress' ?  example:
http://blockdozer.com/insight-api/addr/17Wk4GPKw9nZ9PbspzaxN3fv1L2m9NA9dg/totalReceived



I found this which seems to include sum_value as the equivalent but has more data, was hoping for an example of just getting the total received coins:

https://api.blockchair.com/bitcoin-cash/dashboards/address/17Wk4GPKw9nZ9PbspzaxN3fv1L2m9NA9dg?u=bb76cf81-e618-45b3-988e-42a2bd47538a

**Comment by PorlyBe** [comment]
API documentation would be great, can't wait. Any plans to add Web Socket API as well? Like insight API uses (scroll to bottom above license) https://github.com/bitpay/insight-api/blob/master/README.md

**Comment by anonopanda** [comment]
@JohnnyCashout Do you know if blockchair supports Xpub addresses for Bitcoin Cash?

**Comment by tmaddison** [comment]
@JohnnyCashout I'm interested in an API request to pull Bitcoin Cash number of unconfirmed transactions. Does an API exist for this data?

**Comment by Har01d** [comment]
> I found this which seems to include sum_value as the equivalent but has more data, was hoping for an example of just getting the total received coins without the extra data

No, but you can just parse JSON output.

> Any plans to add Web Socket API as well? Like insight API uses

It’s in the pipeline for the future, but definitely not this year.

> Do you know if blockchair supports Xpub addresses for Bitcoin Cash?

No, we don’t currently support that.

> I'm interested in an API request to pull Bitcoin Cash number of unconfirmed transactions. Does an API exist for this data?

Yes, you can use the following call: https://api.blockchair.com/bitcoin-cash

`{"c":"98","e":"mempool_transactions”}`

— this shows the number of transactions in the mempool.

Please be advised that our API is not for production use, because there can be sudden unannounced changes.

**Comment by kdar** [comment]
Does the site or API provide the current circulating/available supply of bitcoin cash?

**Comment by Har01d** [comment]
We now have some basic API documentation here: https://github.com/Blockchair/Blockchair.Support/blob/master/API.md

> Does the site or API provide the current circulating/available supply of bitcoin cash?

You can calculate it two ways:

1. The fastest is to get the number of blocks using https://api.blockchair.com/bitcoin-cash (`mempool_best_height`). The supply can be approximately calculated this way:
* 50 BTC for blocks #0 — #209999
* 25 BTC for blocks #210000 — #419999
* 12.5 BTC for blocks #420000 — …
… and so on

2. If you need an exact number you can use that call: https://api.blockchair.com/bitcoin/blocks?fields=generation&export=tsv and sum all the values. Why is it more precise? In the early days there were cases when for some reason miners grabbed less coins than they could. But this call is somewhat slow and it's possible we'll turn it off.

Since the total circulating supply is quite a popular request, I guess we'll add it to the basic stats to the https://api.blockchair.com/bitcoin-cash call. I'll update you in this thread when it's ready.

Thank you!

**Comment by MelbourneDeveloper** [comment]
WANT API
WANT API!!!

**Comment by TJ-CoinGecko** [comment]
Is the Bitcoin Cash circulating/available supply api available yet? Simple text page with numbers only will do actually.

**Comment by Har01d** [comment]
We’ve released API v.2 and published detailed documentation available here: https://github.com/Blockchair/Blockchair.Support/blob/master/API.md

> Is the Bitcoin Cash circulating/available supply api available yet? Simple text page with numbers only will do actually.

Yes, now you can use this call: https://api.blockchair.com/bitcoin-cash/stats — it’s in `['data']['circulation']` (in satoshis)
