### ISSUE TITLE
btc cash sent to my personal btc address by error

### ISSUE THREAD

**Issue by velcain29** [Blockchair/Blockchair.Support#1152]
Hi,
Last night, by clumsiness I sent cash btc on my BTC address... I use coinbase as a cryptocurrency wallet and have not received the money.
There are currently 68 confirmations on the transaction to my BTC address, should I wait or try to contact the person with my BTC address as a BTC Cash address (if he answers...)?

**Comment by GarettBill** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by daria-blockchair** [comment]
Hi @velcain29, 

If you have sent Bitcoin Cash or Bitcoin SV to a Bitcoin Segwit-address (an address starting with a 3), it is not possible to recover the funds.
Otherwise, the answer depends on who is the recipient of the transaction:

- You: your private keys (and passphrases) for Bitcoin wallets are valid for Bitcoin Cash and Bitcoin SV wallets and vice versa, so you just need to export and import your keys (passphrases). Please contact your wallet if you need help with this.

- An exchange (Bittrex, Poloniex, Binance, etc.): in this case, you should contact the exchange support.

- Your friend or colleague: you could ask the recipient to install the second wallet and explain that he has to import his private key into that wallet. Please contact your wallet if you need help with this.

**Comment by George43566** [comment]
Send it here let me handle it .bc1qgtwp38q5zhdlmf022my52rla8zzuqgjfc4t6zn
.thank you

**Comment by mhm1likae** [comment]
Hi
