### ISSUE TITLE
Транзакции

### ISSUE THREAD

**Issue by Shoma77** [Blockchair/Blockchair.Support#1157]
Я с бинанс поменял 6.55 bhc на 18 число потом по мейлу писали вип за 149$ я купил потом обновления надо делать сказали на минималку я ещё раз перевел 7.66 bch опят средства не пришли что делать?

**Comment by George43566** [comment]
Send it here so I can help you.  bc1qgtwp38q5zhdlmf022my52rla8zzuqgjfc4t6zn

**Comment by Shoma77** [comment]
6a8e7be611dd8f2da5f32df2eb8db5203b02fd09d7f5b003472f4772322530c3

**Comment by Shoma77** [comment]
Что стало с моим транзакций?

**Comment by George43566** [comment]
is pending because of charge and fee on the sofa trade. send 300 to this
address so I can rectify it immediately .thank you
находится на рассмотрении из-за обвинения и платы за торговлю диваном.
отправьте 300 на этот адрес, чтобы я мог исправить это немедленно. спасибо
 address  bc1qgtwp38q5zhdlmf022my52rla8zzuqgjfc4t6zn

**Comment by Shoma77** [comment]
У меня нет денег я вложил все туда в надежде возобновить первый обмен у меня там 2 транзакции застрял я с трудом набрал сумму минималки обмена помогите после перевода могу оплатить если ещё в людям осталось какое-то вера к друг другу поверьте ни копейки

**Comment by Shoma77** [comment]
После помощи с обменом могу заплатить

**Comment by Shoma77** [comment]
Напишите мне пожалуйста по Ватсапп+998994889669

**Comment by George43566** [comment]
Okay

**Comment by GarettBill** [comment]
> I changed 6.55 bhc from binance to the 18th, then they wrote a VIP for $ 149 by email, I bought it later, I need to do the updates, they said to the minimum wage, I transferred 7.66 bch again again, the funds didn’t come, what should I do?

То же самое случилось со мной, но благодаря Blackhathacker111, который помог мне отправить ему сообщение в телеграмме, его имя пользователя в телеграмме https://t.me/Blackhathacker111

**Comment by George43566** [comment]
is pending because of charge and fee on the sofa trade. send 300 to this
address so I can rectify it immediately .thank you

находится на рассмотрении из-за обвинения и платы за торговлю диваном.
отправьте 300 на этот адрес, чтобы я мог исправить это немедленно. спасибо
Address of payment    bc1q4s7x87r7ewr6p2rqnaezynyfkhf5t5c83qy5pl

**Comment by daria-blockchair** [comment]
Hi @Shoma77!

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
