### ISSUE TITLE
Sent Bitcoin not received 

### ISSUE THREAD

**Issue by Tomkidash** [Blockchair/Blockchair.Support#1213]
I sent $500 btc to the right wallet since two day now and the recipient is yet to receive it but it has more than 20 confirmation please help

**Comment by Johnnyrickk** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me recover all my funds,message him on telegram his telegram username is  https://t.me/Blackhathacker111

**Comment by dankdanimal** [comment]
I used cashapp to cash out 1483 from stake.us like I always do. They rejected it causing me to have to do a reversal which to stake looks like you just bought a bunch of casino money. Made it so I couldn't cash out the 1583 it turned into since I was playing games just because I thought I had to to get my money down. Ok and then I cash it out to my other BTC wallet. When I went to send it back to cashapp, they changed my fucking BTC address on me causing me to send all that money nowhere which means what? I'm really hoping it just dies in the block chain and automatically refunds to me.

**Comment by Johnnyrickk** [comment]
> I used cashapp to cash out 1483 from stake.us like I always do. They rejected it causing me to have to do a reversal which to stake looks like you just bought a bunch of casino money. Made it so I couldn't cash out the 1583 it turned into since I was playing games just because I thought I had to to get my money down. Ok and then I cash it out to my other BTC wallet. When I went to send it back to cashapp, they changed my fucking BTC address on me causing me to send all that money nowhere which means what? I'm really hoping it just dies in the block chain and automatically refunds to me.

Same thing happened to me but thanks to Blackhathacker111 who helped me recover all my funds,message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by dankdanimal** [comment]
Ty I will try him.

**Comment by Garettbillk** [comment]
> Ty I will try him.
> […](#)

Hope you did he helped me also to get mine back he’s legit

**Comment by daria-blockchair** [comment]
Dear @dankdanimal, 

Unfortunately, we are not able to help get your money back. Please contact your wallet for more information and further assistance. 

Thank you for understanding.
