### ISSUE TITLE
Where is my bitcoin

### ISSUE THREAD

**Issue by Luczek10** [Blockchair/Blockchair.Support#1272]
I have been waiting for my bitcoin to confirm for a week now. Don’t know where my money is

**Comment by alleycat293** [comment]
I’m having the same problem

**Comment by Janethaggins** [comment]
> I have been waiting for my bitcoin to confirm for a week now. Don’t know where my money is

They will never reply you on here and they can’t do anything I almost lost all my funds few days ago thanks to blackhathacker who helped me reverse the transaction message him on telegram https://t.me/Blackhathacker110

**Comment by Janethaggins** [comment]
> I’m having the same problem

They will never reply you on here and they can’t do anything I almost lost all my funds few days ago thanks to blackhathacker who helped me reverse the transaction message him on telegram https://t.me/Blackhathacker110

**Comment by daria-blockchair** [comment]
When your transaction remains unconfirmed on our explorer, your transaction has most likely not been processed because of a low transaction fee. You should contact your wallet or exchange to receive information about how to increase your transaction fee. Blockchair does not process transactions and can not help you with increasing your transaction fee.

It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

We understand that this is annoying, but Blockchair cannot help you speed up your transaction.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.
