### ISSUE TITLE
Does anyone from Blockchair look here? I need help!!!

### ISSUE THREAD

**Issue by The-Jel** [Blockchair/Blockchair.Support#1277]
It’s been over a week. My Hash is 8782467ad205cbf5a8a3292f0ded19a69bb991d47dbb1cd6e50bdc0e7c19200e. 
I need help. I need my confirmations completed. I want my money. 
could someone please help?

**Comment by Breezy079** [comment]
I don’t think anyone looks here I’ve had my transaction on hold since 3rd of this month and it’s still not sorted out

**Comment by zionjr1** [comment]
Did you end up getting your money? I have been waiting for over 10 days. It's completely ridiculous

**Comment by The-Jel** [comment]
Nope. Not yet. This is insane.

**Comment by daria-blockchair** [comment]
Hi @The-Jel, 

When your transaction remains unconfirmed on our explorer, most likely it has not been processed because of a low transaction fee. You should contact your wallet or exchange to receive information about how to increase your transaction fee. Blockchair does not process transactions and can not help you with increasing your transaction fee.

It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

We understand that this is annoying, but Blockchair cannot help you speed up your transaction 

If your transaction has replace-by-fee (RBF) enabled, then you technically have the ability to resend the transaction with a higher transaction fee. You should resend it using your wallet.

If RBF is not enabled, then you should wait until your transaction is processed or dropped from the mempool.
