### ISSUE TITLE
Could someone answer my request, please? Someone? My transaction is 9 days old and my queue has not changed. 

### ISSUE THREAD

**Issue by The-Jel** [Blockchair/Blockchair.Support#1281]
My hash is:

8782467ad205cbf5a8a3292f0ded19a69bb991d47dbb1cd6e50bdc0e7c19200e

I really need my money. I’m broke. I need my money.
Please. Someone help me.
I’ve been stuck in the same queue for days.

**Comment by alleycat293** [comment]
Same here

**Comment by daria-blockchair** [comment]
When your transaction remains unconfirmed on our explorer, your transaction has most likely not been processed because of a low transaction fee. You should contact your wallet or exchange to receive information about how to increase your transaction fee. Blockchair does not process transactions and can not help you with increasing your transaction fee.

It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

We understand that this is annoying, but Blockchair cannot help you speed up your transaction.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.
