### ISSUE TITLE
It’s been 15 days. Could someone please confirm my transaction??? Hash: 8782467ad205cbf5a8a3292f0ded19a69bb991d47dbb1cd6e50bdc0e7c19200e

### ISSUE THREAD

**Issue by The-Jel** [Blockchair/Blockchair.Support#1294]
Honestly. This has reached an epic proportion of ridiculous. 
could someone please just have a heart and confirm my withdrawal?
I’m broke and need my funds. 
PLEASE? PLEASE? PLEASE?
Someone. Please help me.

**Comment by daria-blockchair** [comment]
When your transaction remains unconfirmed on our explorer, your transaction has most likely not been processed because of a low transaction fee. You should contact your wallet or exchange to receive information about how to increase your transaction fee. Blockchair does not process transactions and can not help you with increasing your transaction fee.

It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

We understand that this is annoying, but Blockchair cannot help you speed up your transaction.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.
