### ISSUE TITLE
Could someone mark my transaction as “failed”? It’s been 16 days and there has been zero progress in my queue. 

### ISSUE THREAD

**Issue by The-Jel** [Blockchair/Blockchair.Support#1295]
Could someone mark my transaction as “failed”?

It’s been 16 days and there has been no progress in my queue. 

My hash is:

8782467ad205cbf5a8a3292f0ded19a69bb991d47dbb1cd6e50bdc0e7c19200e #1294

**Comment by daria-blockchair** [comment]
When your transaction remains unconfirmed on our explorer, your transaction has most likely not been processed because of a low transaction fee. You should contact your wallet or exchange to receive information about how to increase your transaction fee. Blockchair does not process transactions and can not help you with increasing your transaction fee.

It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

We understand that this is annoying, but Blockchair cannot help you speed up your transaction.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.
