### ISSUE TITLE
Bug: Blockchair turned 546 satoshis into 6.6 BCH

### ISSUE THREAD

**Issue by markblundeberg** [Blockchair/Blockchair.Support#130]
When I opened this page I was surprised to see such a large output amount coming from two tiny inputs.
https://blockchair.com/bitcoin-cash/transaction/252355324

I've included a screenshot of the result:

![screenshot from 2018-08-18 11-46-14](https://user-images.githubusercontent.com/36528214/44302408-b6e89200-a2dc-11e8-8b6c-f9df0a0ad89e.png)

I imagine the bug may have something to do with the usage of OP_RETURN, but I have no idea.

**Comment by Har01d** [comment]
Hello,

Thanks for reporting!

There’s indeed a bug due to one of our databases is malfunctioning. This bug affects approximately 1% of all transactions since this week and represents itself as randomly showing outputs from other transactions.

We’ve fixed this for all new transactions coming to the database, and working on a fix for the previous transactions.

**Comment by Har01d** [comment]
The issue has been fixed for 99% out of this 1% (including the transaction shown on the screenshot). We’re currently reindexing the database, that should fix the rest of transactions.

Once again, thank you for reporting.

**Comment by Har01d** [comment]
Fixed the remainder of malformed transactions.
