### ISSUE TITLE
my transaction is been pending for 3 weeks now i would like for you guys to cancel the transaction

### ISSUE THREAD

**Issue by Ediikr** [Blockchair/Blockchair.Support#1304]
https://blockchair.com/bitcoin/transaction/ff447225a9ba840dd5ec3d11dc826fc6e3b0741cff851c38602ae14e5b81697a
ff447225a9ba840dd5ec3d11dc826fc6e3b0741cff851c38602ae14e5b81697a

Email: imedisonkr@gmail.com

**Comment by daria-blockchair** [comment]
> https://blockchair.com/bitcoin/transaction/ff447225a9ba840dd5ec3d11dc826fc6e3b0741cff851c38602ae14e5b81697a ff447225a9ba840dd5ec3d11dc826fc6e3b0741cff851c38602ae14e5b81697a
> 
> Email: [imedisonkr@gmail.com](mailto:imedisonkr@gmail.com)

When your transaction remains unconfirmed on our explorer, most likely it has not been processed because of a low transaction fee. You should contact your wallet or exchange to receive information about how to increase your transaction fee. Blockchair does not process transactions and can not help you with increasing your transaction fee.

It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

We understand that this is annoying, but Blockchair cannot help you speed up your transaction.
