### ISSUE TITLE
Bitcoin still not confirmed 

### ISSUE THREAD

**Issue by Dirtbagcentral36** [Blockchair/Blockchair.Support#1355]
So my Bitcoin has been on here since the 4th and it's starting to get upsetting that it's not been confirmed even just once or even assigned a number on the blockchain. Can you please send my money to my account? I've been waiting patiently but this is just ridiculous at this point. 
![Screenshot_20231105-105453](https://github.com/Blockchair/Blockchair.Support/assets/149980658/08395391-d532-4c2a-903b-8e15d4e913e7)

**Comment by daria-blockchair** [comment]
> So my Bitcoin has been on here since the 4th and it's starting to get upsetting that it's not been confirmed even just once or even assigned a number on the blockchain. Can you please send my money to my account? I've been waiting patiently but this is just ridiculous at this point. ![Screenshot_20231105-105453](https://user-images.githubusercontent.com/149980658/282222891-08395391-d532-4c2a-903b-8e15d4e913e7.png)

Hi, 
When your transaction remains unconfirmed on our explorer, your transaction has most likely not been processed because of a low transaction fee. You should contact your wallet or exchange to receive information about how to increase your transaction fee. Blockchair does not process transactions and can not help you with processing your transaction faster.
Please find more information [here](https://blockchair.com/faq/why): https://blockchair.com/faq/why and contact your wallet for further assistance. 
Thank you for understanding.
