### ISSUE TITLE
bc1qa4jx5hssgc00ejd346pguhf50nwlclpjdjsc2g

### ISSUE THREAD

**Issue by scott3691** [Blockchair/Blockchair.Support#1383]
This transaction has been sitting since December 9 2023 @ 1:05 am eastern standard time and I have been trying to reach everyone possible to get this resolved I’ve reached out to cash app and stake.us and both tell me it’s here stuck on the blockchain so please I would appreciate it if I can get my money the transaction was in bitcoin and is $380.00 us I won that money and I need it it’s been going on long enough I need some answers asap 
I can be reached by email @ scottcollamore3691@ gmail.com or by phone 4132623162 I live in Massachusetts and I would appreciate it I can get some assistance please thank u !

**Comment by daria-blockchair** [comment]
Hi @scott3691, 

When your transaction remains unconfirmed on our explorer, your transaction has most likely not been processed because of a low transaction fee. You should contact your wallet or exchange to receive information about how to increase your transaction fee. Blockchair does not process transactions and can not help you with increasing your transaction fee.

**Why is my transaction not arriving?**
It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

We understand that this is annoying, but Blockchair cannot help you speed up your transaction → if you continue reading you will find out why your transaction is being processed slowly and what you can do to speed up your transaction.

**Why are transactions being processed slowly?**
Transactions on blockchain networks are processed in blocks and every block has a [block limit](https://blockchair.com/bitcoin/charts/median-block-size) (Bitcoin) or [gas limit](https://blockchair.com/ethereum/charts/median-gas-limit) (Ethereum). This limits the number of transactions that can be processed in a block. In the Bitcoin network, approximately every 10 minutes a new block is processed, with approximately 3,000 transactions in them. In the Ethereum network, approximately every 13 seconds a new block is processed, with currently a maximum of 590 transactions in them.

Currently, there are 231249 transactions in the Bitcoin network waiting to be processed and 68523 transactions in the Ethereum network. The place where non-processed transactions are stored is called the mempool.

To have your transaction prioritized by miners over other transactions, you can attach a transaction fee to your transaction that incentivizes miners to include your transaction in a block quicker. If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.

**What can I do to speed up my transaction?**
- For Bitcoin transactions:
If your transaction has replace-by-fee (RBF) enabled, then you technically have the ability to resend the transaction with a higher transaction fee. You should resend it using your wallet.

If RBF is not enabled, then you should wait until your transaction is processed or dropped from the mempool.

- For Ethereum transactions:
You should increase the transaction fee (gas price). The new parameters should be set in your wallet or by your exchange.

Not every wallet or exchange supports the function to increase the transaction fee. To check whether your wallet or exchange supports increasing the transaction fee or not, you should contact your wallet or exchange. There is nothing Blockchair can do to increase your transaction fee and have your transaction processed faster, unfortunately.

**Warning!**
Beware of scammers! No one can reverse your transaction and only YOU have the power to speed up your transaction. Don’t fall for scammers impersonating members of Blockchair! We will never ask for your private keys, seed phrase or mnemonic phrase. We will not write to you first, be that in a private message on Telegram or other social media.
