### ISSUE TITLE
Wrong Date on Bitcoin Transaction

### ISSUE THREAD

**Issue by sheinix** [Blockchair/Blockchair.Support#1397]
Not sure what's the date displaying in blockchair for [this tx](https://blockchair.com/bitcoin/transaction/124242713043d519449ce469cc76f8eb5ced5ef7ec4585ec437a08c73c65b05b)

I think the date is wrong as it says (at the moment of writing this message) 4 hs ago, but other blockchain explorers show the correct tx age which is: 1m 8 days ago (transaction is stuck)

[Bitaps tx](https://bitaps.com/124242713043d519449ce469cc76f8eb5ced5ef7ec4585ec437a08c73c65b05b)
[Blockchain Tx](https://www.blockchain.com/explorer/transactions/btc/124242713043d519449ce469cc76f8eb5ced5ef7ec4585ec437a08c73c65b05b)

Is this a blockchair bug or something that we are not taking into account?

Thanks

**Comment by Har01d** [comment]
Mempool transactions don't really have a timestamp so we assign the timestamp of the moment when the transaction was processed by our engine. Since we may restart it from time to time, it explains the difference. Once the transaction is confirmed, the timestamp should be the same as with other explorers.
