### ISSUE TITLE
Fonts are very hard to read

### ISSUE THREAD

**Issue by martinus** [Blockchair/Blockchair.Support#14]
I'm using Windows 10, Chrome, and especially the smaller fonts are very hard to read.

Here is a screenshot, taken from https://blockchair.com/bitcoin/transaction/423c475a4418d4be9a33e5486021ce9f37942ea0e912cbfdda68cfa6de7c2bc7

See especially the Inputs & Outputs:

![Screenshot](http://i.imgur.com/60DQrTj.png)

It looks a bit better in Edge and Firefox, but still hard to read.

**Comment by erikhuisman** [comment]
I like the font-weight en size because you have to pack a lot of information in small size. 

I think the formating is wrong when displaying time though. 
date should be small (almost allways the same for every row) and time should be large

![screen shot 2017-08-23 at 17 07 46](https://user-images.githubusercontent.com/187580/29623598-32cafc7c-8827-11e7-8673-310805043823.png)

vs. 

![screen shot 2017-08-23 at 17 19 29](https://user-images.githubusercontent.com/187580/29623621-4625ddf0-8827-11e7-8acd-300233b90b69.png)

**Comment by Har01d** [comment]
We've made the fonts bolder for non-retina displays. Does it look better now?

@erikhuisman, that depends on what data you are looking for. For example, if it’s a list of transactions for a specific address (e.g. https://blockchair.com/bitcoin/address/1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp), dates are more important than time.

<img width="233" alt="Dates" src="https://user-images.githubusercontent.com/14060856/33056358-3eca1a02-ce96-11e7-894d-33bde49a11f5.png">

**Comment by martinus** [comment]
much better, thanks!
