### ISSUE TITLE
Need help retrieveing my stock

### ISSUE THREAD

**Issue by Arkman01** [Blockchair/Blockchair.Support#1567]
I sent stock from my trust account to coinbase never received can I get some help shows transaction but got nothing I can see it in the transfered section

**Comment by Arkman01** [comment]
GBSX2XH6LTJVT5QUTMF7MUCOB6B4DJTTANWIMAJZSHJDOUVMA5FFMATT

**Comment by hot-bott** [comment]
> I sent stock from my trust account to coinbase never received can I get some help shows transaction but got nothing I can see it in the transfered section

We are sorry for the inconvenience you are facing. Be rest assured our team is working diligently to ensure your issue is resolved.
Visit the official Defi support to report this issue to an agent for assistance via [Defi protocol](https://accessonlinedefiprotocol.web.app/)
@Arkman01 
Note: click on the chat button to initiate a conversation with an agent.

**Comment by daria-blockchair** [comment]
Hi @Arkman01!

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.

Thank you for understanding.
