### ISSUE TITLE
Request timeout using the API for both CVS and TSV exports

### ISSUE THREAD

**Issue by Lexus123** [Blockchair/Blockchair.Support#172]
Every time I try the following request, it keeps crashing. Though I get the result on the page itself.

It's quite a small query so it doesn't exceed the 1 million limit.

This is the request:
https://api.blockchair.com/bitcoin/transactions?fields=block_id,hash,time,input_count,cdd_total,input_total,output_total,size&q=output_total(1..),block_id(0..10)&export=csv

**Comment by Har01d** [comment]
Right now it seems everything's working. I guess that was a temporary issue caused by a bug in our database software which we've already fixed.

I'd strongly advise against using using the export feature if you need to retrieve data for a few rows, but for multiple columns. Using JSON API is way more efficient: `https://api.blockchair.com/bitcoin/transactions?q=output_total(1..),block_id(0..10)#`

If you need to get up to 100 rows at once you can additionally use `&limit=<n>`.

The `output_total(1..)` condition seems to be redundant (there's always at least a coinbase transaction which adds 50/25/12.5/… bitcoins to `output_total`.

If you require the entire dataset, it's way better to simply download our database dumps: https://gz.blockchair.com/bitcoin/transactions/

Thanks!

**Comment by Har01d** [comment]
Also please note that CSV export is an undocumented feature and actually sooner or later we'll be deprecating using it without a special API key.
