### ISSUE TITLE
Slow to index the newest block

### ISSUE THREAD

**Issue by dagurval** [Blockchair/Blockchair.Support#2]
The website [bip100.tech](https://bip100.tech) links to blockchair to display block details. However, sometimes clicking on the newest block displayed in a table there will result in 

> Sorry, the page you are looking for could not be found.

Is blockchair slow at indexing new blocks on the network?

**Comment by Har01d** [comment]
The engine works very fast.

The issue here is that the newest block is put into a separate table (https://blockchair.com/bitcoin/mempool/blocks) instead of the main in case of chain reorgs, and the front end doesn’t “see” this block by its height. Currently the latest block can be accessed via its hash: `https://blockchair.com/bitcoin/block/{hash}`

But I’m going to fix this so the newest block could be accessible via its height as well.

**Comment by Har01d** [comment]
Whoops, that was fixed yesterday, I forgot about that :)

Thanks for the report! If you notice any lags with this please let us know.
