### ISSUE TITLE
bitcoin/dashboards/xpub route does not appear to work

### ISSUE THREAD

**Issue by bholzman** [Blockchair/Blockchair.Support#302]
I have not been able to get the bitcoin/dashboards/xpub route to work. Using e.g. the equivalent API call from cryptoapis.io I was able to supply an xpub key and get back the transaction details for addresses descended from that key, but the blockchair API simply returns `data: []` with a `code` of `200`. I've tried both with and without specifying an API key.

**Comment by CryptonightCanada** [comment]
I thought it was an occurance of mine due to using legacy AMD3, 4gb, and an 1980's looking hdd with my faddy coding antiks while swapping hardware with software updates in the background and sync locking my machines then being inpatient and resetting to a bunchmore orphaned files and flaked the filesystem with log currupton over Google Sync

**Comment by bholzman** [comment]
Ah, figured it out -- I needed to convert the xpub to a zpub.
