### ISSUE TITLE
Dashboard address info - HTTP 500 Internal Server Error 

### ISSUE THREAD

**Issue by jvalteren** [Blockchair/Blockchair.Support#352]
Dear Blockchair team,

We're using your API to track balances of several cryptocurrency addresses (currently Bitcoin and Ethereum/ERC-20). An API call to the dashboard endpoints for Bitcoin and Ethereum is made regularly (both on a schedule and on-demand).

Lately (read: since a couple of weeks) we've been getting HTTP 500 Internal Server Error responses to some of these calls. This seems to coincide with high trading volume in Bitcoin and/or Ether. Today 8 February 2021, this started occurring again at 14:15 CET. We've had 9 errors returned so far, between 14:15 and 14:44 CET. 

The error occurs with both Bitcoin and Ethereum address info endpoints, with multiple different addresses.

The HTTP status code is 500, with reason 'Internal Server Error'. The response payload contains the following JSON:
```
{"data":null,"context":{"code":500,"error":"Something went wrong"}}
```

This is interfering with the correct operation of our application. We are on a paid plan for 5000 requests/day. Can you please investigate and correct this situation as soon as possible.

PS Besides this issue, we're very happy with your service! Keep up the good work!!

Kind regards,
Jonathan

**Comment by Har01d** [comment]
Hello,

Today between 12:14 and 12:24 UTC we’ve noticed an elevated error rate due to some networking issues in our data center (some of our back end servers experienced dropped packets when connected to other back end servers in another location). That led to the issue you are describing. Same issue was present a day ago in the middle of the night.

We’re in the process of moving our primary infrastructure to another data center with better networking stability.

Sorry for the inconvenience.

**Comment by jvalteren** [comment]
Hi @Har01d,

Thank you for your quick reply. Can you tell me what the planning is for the infrastructure upgrade? In other words, when can we expect the issue to be resolved?

Best,
Jonathan

**Comment by Har01d** [comment]
Hi Jonathan,

The issue is not persistent and has been resolved. There’s no precise ETA on the upgrade, but we’ve already started working on it.
