### ISSUE TITLE
Transaction hash

### ISSUE THREAD

**Issue by jcrojas98** [Blockchair/Blockchair.Support#426]
I made a bitcoin transaction and it is pending but it doesn't show the transaction hash. Why is this happening? #not found hash

**Comment by daria-blockchair** [comment]
Hi, 

If you can't find a transaction hash on the platform from which you initiated a transaction, please contact the support of your wallet or exchange for more information. In case when you search for your tx hash on blockchair.com and you get "No result", then the transaction either was never sent out, dropped from the mempool, or just hasn’t reached our mempool yet. Unfortunately, I can not provide you with more details, since I don't have your tx hash.

Thank you for understanding.

Best regards
