### ISSUE TITLE
How do I contact regarding a big error on sending my crypto?

### ISSUE THREAD

**Issue by Ezcompany760** [Blockchair/Blockchair.Support#662]
DDUoTGov76gcqAEBXXpUHzSuSQkPYKze9N

I messed up bad, extremely new to all this and somehow sent my crypto approx $830 worth BACK into the dogecoin block chain, when it was supposed to send to my Coinbase. Am I SOL on this or can anything be done? I have all the links verifying the transactions

**Comment by Emimendoza** [comment]
Unfortunately crypto is decentralized. If you  did a transaction and it got verified there is nothing that can be done since no one can undue a transaction. If you know who owns the wallet you sent the dogecoin to, you can ask them and they can send it to you back if they want to. Nobody except the person who owns the wallet can take out money from it.

**Comment by daria-blockchair** [comment]
Hi @Ezcompany760, 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
